### ISSUE TITLE
Enhacement show hide filter header

### ISSUE THREAD

**Issue by lipodido** [melistik/vaadin-grid-util#1]
Can you please add function like setFilterBarVisible    to show hide filter Row
Thanks in advance

**Comment by melistik** [comment]
will be part of next release

**Comment by melistik** [comment]
Hi I've implemented a version of this feature. Badfully the Grid itself has no function to allow changing the visibility that's why i needed to remove or recreate the hole HeaderRow. During the remove of the row the registered connectors of each FilterCell log an error message in the console. I haven't found a way to avoid this. Still I commited my code (as a deprecated function) so that maybe anyone else can solve this issue...
